from abc import ABC, abstractmethod
from typing import List, Optional
import time
import functools

def rate_limited(max_retries: int = 3, initial_delay: float = 1.0):
    """
    Decorator to handle rate limiting and retries for LLM API calls.
    
    Args:
        max_retries: Maximum number of retry attempts
        initial_delay: Initial delay between retries in seconds
    """
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            for attempt in range(max_retries):
                try:
                    result = func(*args, **kwargs)
                    # Short pause after successful call
                    time.sleep(0.1)
                    return result
                except Exception as e:
                    error_msg = str(e).lower()
                    if ("rate limit" in error_msg or "quota" in error_msg) and attempt < max_retries - 1:
                        wait_time = initial_delay * (2 ** attempt)
                        print(f"Rate limit hit. Waiting {wait_time:.1f} seconds...")
                        time.sleep(wait_time)
                        continue
                    if attempt == max_retries - 1:
                        raise Exception(f"Failed after {max_retries} retries: {str(e)}")
                    raise
        return wrapper
    return decorator


class LLMAgent(ABC):
    """Abstract interface for LLM agents"""
    
    @abstractmethod
    def initialize(self) -> None:
        """Initialize the agent with its required configurations"""
        pass
    
    @abstractmethod  
    def generate_response(self, question: str, context: Optional[str] = None) -> str:
        """Generate a response to a question with optional context
        
        Args:
            question: The question asked by the user
            context: Optional context to provide to the LLM
            
        Returns:
            str: The response generated by the LLM
        """
        pass
    
    @property
    @abstractmethod
    def model_name(self) -> str:
        """Return the model name for identification"""
        pass